<?php

?>

</pre>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Error</title>
    <link rel="stylesheet" href="static/stylesheets/errors.css" />
    <link
      href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="error-page">
      <div class="error-img">
        <img src="/static/images/errorCats.jpg" alt="Sad Cats" class="cats" />
      </div>
      <div class="Err-Message">
        <div class="ups">Ups, there is some error</div>

        <div class="code">400 Bad Request</div>
      </div>
    </div>
  </body>
</html>